### ISSUE TITLE
UI 에서 POD 추가시 에러

### ISSUE THREAD

**Issue by kimscott** [TheOpenCloudEngine/uEngine-cloud-k8s#17]
추가를 1번은 정상적으로 날라가는데,
화면을 리프레쉬 안시키고 다시 add 버튼을 눌러서 pod 추가시
팝업창이 안닫히고, 생성도 안됨

**Comment by kimscott** [comment]
삭제버튼을 누른 후 add 버튼 정상적으로 작동 안함

**Comment by kimsanghoon1** [comment]
EventBus 수정
