### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by kimsanghoon1** [TheOpenCloudEngine/uEngine-cloud-k8s#8]
## pod list
![pod-list](https://user-images.githubusercontent.com/16382067/54254278-8b8a0500-4596-11e9-825b-2d874f59392f.png)

## pod editor
![pod-editor](https://user-images.githubusercontent.com/16382067/54254317-a65c7980-4596-11e9-804f-ebdef109e6f8.png)

## deploy list
![depl-list](https://user-images.githubusercontent.com/16382067/54254405-e7ed2480-4596-11e9-87ab-6f8685ffabd2.png)

## deploy editor
![depl-editor](https://user-images.githubusercontent.com/16382067/54254558-87121c00-4597-11e9-8dd6-26f97590ff1f.png)

## service list
![svc-list](https://user-images.githubusercontent.com/16382067/54254427-06532000-4597-11e9-8bf0-7e33390aaff0.png)

## service editor
![svc-editor](https://user-images.githubusercontent.com/16382067/54254472-2f73b080-4597-11e9-95da-1bcecea69480.png)

## sample
![image](https://user-images.githubusercontent.com/16382067/54254530-6649c680-4597-11e9-8b20-5dbf7ea51902.png)

**Comment by jinyoung** [comment]
![image](https://user-images.githubusercontent.com/487999/54256571-cfcdd300-459f-11e9-89d3-c457a50676c0.png)

![image](https://user-images.githubusercontent.com/487999/54256645-0e638d80-45a0-11e9-9e09-74b2fece8956.png)
